services:
  - type: web
    name: v65-binance-gold-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements_render.txt
    startCommand: python V65_binance_render.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /
